name: Nix GH Action 
on: [push]
jobs:
  test-inside-nix:
    runs-on: ubuntu-latest
    environtment: MAIN
    steps:
    - uses: actions/checkout@v2.4.0
    - id: auth
      uses: 'google-github-actions/auth@v0'
      with: 
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run "gcloud info"