name: Nix GH Action 
on: [push]
jobs:
  test-inside-nix:
    runs-on: ubuntu-latest
    environment: MAIN
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: echo "system-features = nixos-test benchmark big-parallel kvm" > /etc/nix/nix.conf
    - run: ./build.sh
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - id: auth
      uses: 'google-github-actions/auth@v0'
      with: 
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - run: npm install 
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}