name: Nix GH Action 
on: [push]
jobs:
  test-inside-nix:
    runs-on: ubuntu-latest
    environment: MAIN
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: 'google-github-actions/auth@v0'
      with: 
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run "pulumi stack select dev && pulumi preview"
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}